name: Hello World on PR Comment

on:
  issue_comment:
    types:
      - created

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
